[build]
  command = "npm run build:netlify"
  functions = "lambda"
  publish="public"

[dev]
  command = "npm run serve"
  port = 4444
  publish = "public"
  functionsPort = 9000

[production]
  command = "npm run build:netlify"
  publish = "public"
