[build]
  command = "npm run build:netlify"
  publish="public"

[dev]
  command = "npm run serve"
  port = 3000
  publish = "public"

[production]
  command = "npm run build:netlify"
  publish = "public"
